# Generated by Django 5.2.6 on 2025-10-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_post_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='uploaded_at',
        ),
    ]
