# Generated by Django 5.2.6 on 2025-10-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_appliedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
