# Generated by Django 5.2.6 on 2025-09-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOtp',
        ),
    ]
