# Generated by Django 5.2.6 on 2025-09-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOtp',
        ),
    ]
