# Generated by Django 5.2.6 on 2025-10-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingUser',
        ),
    ]
