# Generated by Django 5.2.6 on 2025-10-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_companyprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='description',
            new_name='about_us',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_name',
        ),
    ]
