# Generated by Django 5.2.6 on 2025-10-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
